### ISSUE TITLE
Feat Req: filenames minimal

### ISSUE THREAD

**Issue by nuke-web3** [paritytech/prdoc#12]
Tiny nit, while still early: IMHO the `pr_###.prdoc` is kinda redundant. We should rather just use the PR number as the file name, and perhaps a `README.md` in the repo this is used in located in `./prdoc/...` that describes the TLDR of what these files are and points to this repo.

**Comment by chevdor** [comment]
Yes, I cannot really disagree but that will be transparent to the user using `prdoc` to generate a new prdoc since the name is generate for you.

With the new version I am working on in #13, users won't need to provide the prdoc folder at alll, this will be part of the config and defined per repo.

**Comment by mutantcornholio** [comment]
Outdated: we aren't providing file name anymore
